name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1
outputs:
  pokemon_name:
    description: 'Name des Pokemons'
    value: ${{ steps.pokemon_name.outputs.pokemon_name }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - id: pokemon_name
      run: |
         pokemon_name=2
         echo $pokemon_name
         echo "::set-output name=pokemon_name::$pokemon_name"
      shell: bash
