name: app2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'devl'
        required: true
        default: 'devl'
env:
   test: suresh
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          echo $test
          echo $environment
          echo Hello, world!
        

  DeployDev:
    name: Deploy to Dev 
    if: ${{ github.event.ref == 'refs/heads/master' || github.event.inputs.environment  == 'devl' }}
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo $test
          echo I am deploying! 

  Deployprod:
    name: Deploy to prod
    if: ${{ github.event.ref == 'refs/heads/main' }}
    needs: [Build,DeployDev]
    runs-on: ubuntu-latest
  
    environment: prod
    steps:
      - name: Deploy
        run: echo I am prod!
