name: app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev 
    if: github.ref == 'refs/heads/^((?!^master$).)*$'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy
        run: echo I am deploying! 

  Deployprod:
    name: Deploy to prod
    needs: [Build,DeployDev]
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/main }}
    environment: prod
    steps:
      - name: Deploy
        run: echo I am prod! 
