name: test

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
    - name: nodejs
      uses: sureshdec/ActionTemaplate/.github/actions/nodesetup@main
      with:
       node-version: '12.22.1'
