name: test

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
    - name: nodejs
      id: pokemon
      uses: sureshdec/ActionTemaplate/.github/actions/output@main
      with:
       pokemon_id: 5
    - run: run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
