# This is a basic workflow to help you get started with Actions

name: DI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]

  workflow_dispatch:
jobs:
  edl-files-loader:
   runs-on: ubuntu-latest
   strategy:
      matrix:
          config:
          - {region: us-east-1, currentEnvName: devl, s3Bucket: jd-us01-commoninformationservices-devl-system, fileName: infrastructure/cloudformation_templates/edl-entitlement-key-manager.json, stackName: edl-entitlement-key-manager }
          - { region: us-east-1, currentEnvName: prod, s3-bucket: jd-us01-cis-devl-entitlement-keys, fileName: infrastructure/cloudformation_templates/edl-entitlement-key-manager-devl.json, stackName: edl-entitlement-key-manager }
          - { region: us-east-1, currentEnvName: devl, s3-bucket: jd-us01-commoninformationservices-devl-system, fileName: infrastructure/cloudformation_templates/edl-entitlement-key-manager.json, stackName: edl-entitlement-key-manager }
          - { region: us-east-1, currentEnvName: prod, s3-bucket: jd-us01-cis-devl-entitlement-keys, fileName: infrastructure/cloudformation_templates/edl-entitlement-key-manager-devl.json, stackName: edl-entitlement-key-manager }
       
       
   steps:
   - name: Git checkout
     uses: actions/checkout@v2
   - name: ${{ matrix.currentEnvName }}
     run: |
       echo ${{ matrix.currentEnvName }}

         
