name: test3

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      env:
        description: 'devl | prod'
        required: true
        default: 'devl'

jobs:
  test3:
   runs-on: [ ubuntu-latest ]
   steps:
   - uses: actions/checkout@v2
   - name: Get Current Date - Staging Script.
     id: date
     run: echo "::set-output name=date::$(date +%s)"
   - name: print
     run: |
       echo ${{ steps.date.outputs.date }}
   - name: devl
     if: ${{ github.event.inputs.env == 'devl' &&
       (github.event.ref == 'refs/heads/dev' || github.event.ref == 'refs/heads/development' || github.event.ref == 'refs/heads/optimize') }}
     run: |
       echo "devl"
   - name: prod
     if: ${{ github.event.inputs.env == 'prod' && github.event.ref == 'refs/heads/dev' }}
     run: |
       echo "prod"
