name: test6

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
 runOnce: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: sureshdec/ActionTemaplate/.github/workflows/test.yml@master
        with:
          ENVIRONMENT: devl

         
         
