name: edl-core-grants

# Controls when the workflow will run
on:
  # Triggers the workflow on push event for any branch or pull request event but only for the master branch
  push:
     branches:
      - "*"
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
jobs:
  devl:
   runs-on: ubuntu-latest
   steps:
    - name: checkout 
      uses: actions/checkout@v2 
    - name: dev deploy
      run: |
        echo "devl"
  prod:
   runs-on:  ubuntu-latest
   needs: devl
   steps:
    - name: checkout 
      uses: actions/checkout@v2 
    - name: prod deploy
      if: ${{ github.event.ref == 'refs/heads/master' && success() }}
      run: |
        echo "prod"
